---
permalink: online-help/concept-all-workloads.html 
sidebar: sidebar 
keywords: workloads,workloads 
summary: 모든 워크로드 보기에는 데이터 센터의 클러스터에서 사용 가능한 모든 워크로드 목록이 표시됩니다. 
---
= 모든 워크로드
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
모든 워크로드 보기에는 데이터 센터의 클러스터에서 사용 가능한 모든 워크로드 목록이 표시됩니다.

모든 워크로드 보기에는 Unified Manager에서 관리하는 ONTAP 클러스터와 관련된 스토리지 워크로드가 나열됩니다. 또한 스토리지 워크로드에 스토리지 효율성 정책 및 성능 서비스 수준을 할당할 수 있습니다.

Unified Manager에 클러스터를 추가하면 FlexGroup 볼륨 및 구성 구성요소를 제외한 각 클러스터의 스토리지 워크로드가 자동으로 검색되어 이 페이지에 표시됩니다.

Unified Manager는 스토리지 워크로드에서 I/O 작업이 시작된 후에만 권장 성능 서비스 수준(권장 성능 서비스 수준)에 대한 워크로드를 분석하기 시작합니다. I/O 작업이 없는 새로 발견된 스토리지 워크로드의 경우 I/O를 기다리는 중입니다. 스토리지 워크로드에서 I/O 작업이 시작되면 Unified Manager가 분석을 시작하고 워크로드 상태가 ""학습...""으로 변경됩니다. 분석이 완료되면(I/O 작업 시작 후 24시간 이내) 스토리지 워크로드에 대해 권장되는 성능 서비스 수준이 표시됩니다.

워크로드 * > * 모든 워크로드 * 옵션을 사용하여 여러 작업을 수행할 수 있습니다.

* 스토리지 워크로드를 추가하거나 프로비저닝
* 워크로드 목록을 보고 필터링합니다
* 개별 스토리지 워크로드에 성능 서비스 수준을 할당합니다
* 할당되지 않은 모든 워크로드에 시스템 권장 성능 서비스 수준 할당
* 스토리지 효율성 정책을 스토리지 워크로드에 할당합니다




== 스토리지 워크로드 추가 또는 프로비저닝

지원되는 LUN(iSCSI 및 FCP 프로토콜 모두 지원), NFS 파일 공유 및 SMB 공유에 스토리지 워크로드를 추가하거나 프로비저닝할 수 있습니다.



== 워크로드 보기 및 필터링

모든 워크로드 화면에서 데이터 센터의 모든 워크로드를 확인하거나 할당된 성능 서비스 수준 또는 워크로드 이름을 기준으로 특정 스토리지 워크로드를 검색할 수 있습니다. 필터 아이콘을 사용하여 검색에 대한 특정 조건을 입력할 수 있습니다. 호스트 클러스터나 스토리지 VM과 같은 다양한 필터 조건으로 검색할 수 있습니다. Capacity Total * 옵션을 선택하면 워크로드의 총 용량별로 검색할 수 있습니다. 반환되는 워크로드 수는 용량이 바이트 레벨에서 비교되므로 정확한 필터 조건에 따라 달라질 수 있습니다. 이 화면에는 호스트 클러스터 및 스토리지 VM과 같은 워크로드에 대한 스토리지 정보와 함께 성능 서비스 수준 및 스토리지 효율성 정책(있는 경우)이 표시됩니다.

또한 이 페이지에서는 워크로드의 성능 세부 정보를 볼 수 있습니다. 열 선택/주문 * 버튼을 클릭하고 표시할 특정 열을 선택하여 워크로드의 IOPS, 용량, 지연 시간에 대한 자세한 정보를 볼 수 있습니다. 성능 보기 열에는 워크로드에 대한 평균 및 최대 IOPS가 표시되며, 워크로드 분석기 아이콘을 클릭하여 자세한 IOPS 분석을 볼 수 있습니다. IOPS 분석 팝업의 * 워크로드 분석 * 버튼을 누르면 워크로드 분석 페이지로 이동합니다. 이 페이지에서 시간 범위를 선택하고 선택한 워크로드의 지연 시간, 처리량, 용량 추세를 확인할 수 있습니다. 워크로드 분석기에 대한 자세한 내용은 _ 워크로드 분석기를 사용한 워크로드 문제 해결 _ 을(를) 참조하십시오

link:concept-troubleshooting-workloads-using-the-workload-analyzer.adoc["워크로드 분석기를 사용하여 워크로드 문제 해결"]



== 스토리지 워크로드에 성능 서비스 수준 할당

단일 또는 여러 스토리지 워크로드에 성능 서비스 수준을 할당할 수 있습니다. 화면에서 다른 탐색을 사용하여 워크로드에 특정 또는 시스템 권장 성능 서비스 수준을 할당할 수 있습니다.



== 할당되지 않은 모든 워크로드에 시스템 권장 성능 서비스 수준 할당

워크로드에 사용 가능한 시스템 권장 성능 서비스 수준이 있는 경우 PSL이 할당되지 않은 데이터 센터의 모든 스토리지 워크로드에 성능 서비스 수준을 할당할 수 있습니다. 이 기능은 시스템에서 권장하는 성능 서비스 수준이 없는 워크로드에 대해서는 적용되지 않습니다. 이 기능을 사용하려면 * 시스템 권장 PSL 할당 * 버튼을 클릭합니다. 시스템에서 할당되지 않은 스토리지 워크로드에 대해 적절한 성능 서비스 수준을 내부적으로 평가하고 성능 서비스 수준을 할당할 수 있는 총 워크로드 수를 표시합니다.



== 스토리지 워크로드에 스토리지 효율성 정책 할당

단일 또는 여러 스토리지 워크로드에 스토리지 효율성 정책을 할당할 수 있습니다. 화면의 다양한 탐색 기능을 사용하여 스토리지 워크로드에 특정 스토리지 효율성 정책을 할당할 수 있습니다.



== 성능 서비스 수준 및 스토리지 효율성 정책을 함께 할당합니다

단일 워크로드에 성능 서비스 수준 및 스토리지 효율성 정책을 함께 할당할 수 있습니다. 다음 단계를 수행하십시오.

. 행의 편집 아이콘을 클릭한 다음 * 편집 * 을 클릭합니다.
+
할당된 성능 서비스 수준 * 및 * 스토리지 효율성 정책 * 필드가 활성화됩니다.

. 필요한 성능 서비스 수준 및 스토리지 효율성 정책을 선택합니다.
. 확인 아이콘을 클릭하여 변경 사항을 적용합니다.




== 워크로드에 대한 성능 및 용량 기준 분석

성능 보기 * 열에서 막대 차트 아이콘을 클릭하여 문제 해결에 도움이 되는 작업 부하에 대한 성능 정보를 볼 수 있습니다. 워크로드 분석 페이지에서 성능 및 용량 차트를 보고 객체를 분석하려면 * 워크로드 분석 * 버튼을 클릭합니다.
