---
permalink: online-help/concept-monitoring-vms.html 
sidebar: sidebar 
keywords: virtual machines 
summary: '가상 머신 \(VM\) 애플리케이션에서 지연 시간 문제가 발생하는 경우 VM을 모니터링하여 원인을 분석하고 문제를 해결해야 할 수 있습니다.' 
---
= 가상 머신 모니터링
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
가상 머신(VM) 애플리케이션에서 지연 시간 문제가 발생하는 경우 VM을 모니터링하여 원인을 분석하고 문제를 해결해야 할 수 있습니다.

Active IQ Unified Manager를 사용하면 VM과 관련된 구성 요소(예: VM의 호스트 또는 VM에 연결된 데이터 저장소)를 표시하는 VM 애플리케이션의 세부 토폴로지를 볼 수 있습니다. 토폴로지 뷰는 특정 계층의 기본 구성 요소를 다음 순서로 표시합니다. * 가상 디스크 * > * VM * > * 호스트 * > * 네트워크 * > * 데이터 저장소 * > * VMDK *.

[NOTE]
====
스토리지 계층에서 데이터 저장소의 메트릭을 보려면 Unified Manager에 상위 ONTAP 클러스터를 추가해야 하며, 클러스터에 대한 검색(폴링 또는 메트릭 수집)이 완료되었는지 확인해야 합니다.

====
토폴로지 측면에서 I/O 경로와 구성 요소 레벨 지연 시간을 확인하고 스토리지가 성능 문제의 원인인지 여부를 식별할 수 있습니다. 토폴로지의 요약 보기에는 I/O 경로가 표시되며, 문제 해결 단계를 결정할 때 IOPS 및 지연 시간 문제가 있는 구성 요소가 강조 표시됩니다. 또한 각 구성 요소를 별도로 설명하는 토폴로지와 해당 구성 요소의 지연 시간을 볼 수 있습니다. 계층을 통해 강조 표시된 I/O 경로를 결정하기 위해 구성 요소를 선택할 수 있습니다.



== vCenter 데이터 수집 스케줄입니다

vCenter 구성 데이터를 폴링하기 위해 Unified Manager는 클러스터 구성 데이터를 수집하는 것과 동일한 스케줄을 따릅니다. vCenter 구성 및 성능 데이터 수집 스케줄에 대한 자세한 내용은 "클러스터 구성 및 성능 데이터 수집 작업"을 참조하십시오.

vCenter는 20초 간의 실시간 성능 데이터 샘플을 수집하여 최대 5분 분량의 샘플을 취합합니다. Unified Manager의 성능 데이터 수집 일정은 vCenter Server의 기본 설정을 기반으로 합니다. Unified Manager는 vCenter에서 얻은 5분 샘플을 처리하고, 가상 디스크, VM 및 호스트에 대한 IOPS 및 지연 시간의 시간별 평균을 계산합니다. 데이터 저장소의 경우 Unified Manager는 ONTAP에서 얻은 샘플에서 IOPS 및 지연 시간의 시간별 평균을 계산합니다. 이러한 값은 시간 맨 위에 표시됩니다. vCenter를 추가한 직후에 성능 메트릭을 사용할 수 없으며 다음 시간이 시작될 때만 사용할 수 있습니다. 성능 데이터 폴링은 구성 데이터 수집 주기를 완료하는 데 시작됩니다.



== 요약 토폴로지 보기

VM을 요약 토폴로지로 확인하여 성능 문제를 파악합니다

. VMware * > * 가상 머신 * 으로 이동합니다.
. 검색 상자에 VM 이름을 입력하여 VM을 검색합니다. 필터 * 버튼을 클릭하여 특정 기준에 따라 검색 결과를 필터링할 수도 있습니다. 그러나 VM을 찾을 수 없는 경우 해당 vCenter가 추가되고 검색되었는지 확인합니다.
+
[NOTE]
====
vCenter Server는 특수 문자(예: %, &, *, $, #, @,!,\, /,:, *,?,"",<,>, |,;,') VM, 클러스터, 데이터 저장소, 폴더, 또는 파일. VMware vCenter Server 및 ESX/ESXi Server는 표시 이름에 사용되는 특수 문자를 이스케이프하지 않습니다. 하지만 Unified Manager에서 이름을 처리하면 이름이 다르게 표시됩니다. 예를 들어, 이라는 이름의 VM이 있습니다 `%$VC_AIQUM_clone_191124%` vCenter Server에서 가 로 표시됩니다 `%25$VC_AIQUM_clone_191124%25` 볼 수 있습니다. 이름에 특수 문자가 포함된 VM을 쿼리할 때 이 문제를 기록해 두어야 합니다.

====
. VM의 상태를 확인합니다. vCenter에서 VM 상태를 검색합니다. 다음 상태를 사용할 수 있습니다. 이러한 상태에 대한 자세한 내용은 VMware 설명서를 참조하십시오.
+
** 정상
** 경고
** 경고
** 모니터링되지 않음
** 알 수 없음


. VM 옆의 아래쪽 화살표를 클릭하여 컴퓨팅, 네트워크 및 스토리지 계층 전체에서 구성 요소 토폴로지에 대한 요약 보기를 표시합니다. 지연 시간 문제가 있는 노드가 강조 표시됩니다. 요약 보기에는 구성 요소의 지연 시간이 가장 짧습니다. 예를 들어, VM에 가상 디스크가 두 개 이상 있는 경우 이 보기에는 모든 가상 디스크 중에서 지연 시간이 가장 짧은 가상 디스크가 표시됩니다.
. 일정 기간 동안 데이터 저장소의 지연 시간 및 처리량을 분석하려면 데이터 저장소 개체 아이콘 위에 있는 * Workload Analyzer * 버튼을 클릭합니다. 워크로드 분석 페이지로 이동하여 시간 범위를 선택하고 데이터 저장소의 성능 차트를 확인할 수 있습니다. 워크로드 분석기에 대한 자세한 내용은 _ 워크로드 분석기를 사용한 워크로드 문제 해결 _ 을(를) 참조하십시오.
+
link:concept-troubleshooting-workloads-using-the-workload-analyzer.adoc["워크로드 분석기를 사용하여 워크로드 문제 해결"]





== 확장된 토폴로지 보기

VM의 확장된 토폴로지를 확인하여 각 구성 요소별로 드릴다운할 수 있습니다.

. 요약 토폴로지 보기에서 * 토폴로지 확장 * 을 클릭합니다. 각 구성 요소의 상세한 토폴로지와 각 개체의 지연 시간 번호를 별도로 확인할 수 있습니다. 데이터 저장소 또는 VMDK에 여러 노드 같은 범주에 여러 노드가 있는 경우 지연 시간이 가장 짧은 노드는 빨간색으로 강조 표시됩니다.
. 특정 객체의 입출력 경로를 확인하려면 해당 객체를 클릭하여 입출력 경로와 해당 매핑을 확인하십시오. 예를 들어, 가상 디스크의 매핑을 보려면 가상 디스크를 클릭하여 해당 VMDK에 대한 강조 표시된 매핑을 확인합니다. 이러한 구성 요소의 성능이 저하될 경우 ONTAP에서 더 많은 데이터를 수집하고 문제를 해결할 수 있습니다.
+
[NOTE]
====
vmdks에 대한 메트릭은 보고되지 않습니다. 토폴로지에서는 VMDK 이름만 표시되고 메트릭은 표시되지 않습니다.

====

