---
permalink: online-help/concept-managing-storage-efficiency-policies.html 
sidebar: sidebar 
keywords: add 
summary: 'SEP(Storage Efficiency Policy\)를 사용하면 워크로드의 스토리지 효율성 특성을 정의할 수 있습니다. 워크로드를 처음 생성할 때 또는 나중에 워크로드를 편집하여 스토리지 효율성 정책을 워크로드에 할당할 수 있습니다.' 
---
= 스토리지 효율성 정책 관리
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SEP(Storage Efficiency Policy)를 사용하면 워크로드의 스토리지 효율성 특성을 정의할 수 있습니다. 워크로드를 처음 생성할 때 또는 나중에 워크로드를 편집하여 스토리지 효율성 정책을 워크로드에 할당할 수 있습니다.

스토리지 효율성에는 스토리지 활용률을 높이고 스토리지 비용을 절감하는 씬 프로비저닝, 중복제거, 데이터 압축 등의 기술 사용이 포함됩니다. 스토리지 효율성 정책을 생성하는 동안 이러한 공간 절약 기술을 개별적으로 또는 함께 사용하여 스토리지 효율성을 극대화할 수 있습니다. 정책을 스토리지 워크로드와 연결하면 지정된 정책 설정이 해당 정책에 할당됩니다. Unified Manager를 사용하면 시스템 정의 및 사용자 정의 스토리지 효율성 정책을 할당하여 데이터 센터의 스토리지 리소스를 최적화할 수 있습니다.

Unified Manager는 두 가지 시스템 정의 스토리지 효율성 정책, 즉 High와 Low를 제공합니다. 이러한 CDP는 데이터 센터의 스토리지 워크로드 대부분에 적용할 수 있지만, 시스템 정의 CDP가 요구사항을 충족하지 않는 경우 자체 정책을 생성할 수 있습니다.

시스템 정의이거나 현재 워크로드에 할당된 스토리지 효율성 정책은 수정할 수 없습니다. 워크로드에 할당된 스토리지 효율성 정책이나 사용 가능한 스토리지 효율성 정책만 삭제할 수는 없습니다.

스토리지 효율성 정책 페이지에는 사용 가능한 스토리지 효율성 정책이 나열되어 있으며 사용자 지정 CDP를 추가, 편집 및 삭제할 수 있습니다. 이 페이지에는 다음 정보가 표시됩니다.

[cols="1a,1a"]
|===
| 필드에 입력합니다 | 설명 


 a| 
이름
 a| 
스토리지 효율성 정책의 이름입니다.



 a| 
유형
 a| 
정책이 시스템 정의인지 사용자 정의인지 여부



 a| 
공간 예약
 a| 
볼륨이 씬 프로비저닝되었는지 아니면 일반 프로비저닝되었는지 여부



 a| 
중복 제거
 a| 
볼륨에 중복제거가 활성화되어 있는지 여부:

* `Inline`: 중복 제거는 볼륨에 쓰는 동안 발생합니다
* `Background`: 중복 제거는 백그라운드에서 수행됩니다
* `Disable`: 볼륨에서 중복 제거가 비활성화되었습니다




 a| 
압축
 a| 
볼륨에 데이터 압축이 활성화되어 있는지 여부:

* `Inline`:볼륨에 쓰는 동안 데이터 압축이 발생합니다
* `Background`: 데이터 압축은 백그라운드에서 실행됩니다
* `Disable`: 볼륨에서 데이터 압축이 비활성화됩니다




 a| 
워크로드
 a| 
스토리지 효율성 정책이 할당된 스토리지 워크로드 수입니다

|===


== 맞춤형 스토리지 효율성 정책을 생성하기 위한 지침입니다

기존 스토리지 효율성 정책이 스토리지 워크로드의 정책 요구사항을 충족하지 않는 경우 맞춤형 스토리지 효율성 정책을 생성할 수 있습니다. 하지만 스토리지 워크로드에 시스템 정의 스토리지 효율성 정책을 사용하고 필요한 경우 맞춤형 스토리지 효율성 정책만 생성하는 것이 좋습니다.
