---
permalink: online-help/task-provisioning-fileshares.html 
sidebar: sidebar 
keywords:  
summary: '워크로드 프로비저닝 페이지에서 사용 가능한 여유 공간이 있는 경우 기존 클러스터 및 스토리지 가상 머신\(스토리지 VM\)에 대한 LUN\(iSCSI 및 FCP 프로토콜 모두 지원\) 또는 파일 공유\(CIFS/SMB 및 NFS 프로토콜 지원\)를 생성할 수 있습니다.' 
---
= 워크로드 프로비저닝
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Provision Workload 페이지에서는 사용 가능한 공간이 있을 때 기존 클러스터 및 스토리지 가상 머신(스토리지 VM)에 대한 LUN(iSCSI 및 FCP 프로토콜 모두 지원) 또는 파일 공유(CIFS/SMB 및 NFS 프로토콜 지원)를 생성할 수 있습니다.



== 시작하기 전에

* 스토리지 VM에서 하나 이상의 SMB, NFS, iSCSI 및 FCP 서비스 또는 모든 서비스를 활성화해야 합니다. LUN을 생성하는 경우 iSCSI와 FCP를 모두 사용하도록 설정해야 합니다.
* 워크로드에 대한 성능 서비스 수준 및 스토리지 효율성 정책을 선택하고 할당하려면 워크로드를 생성하기 전에 정책을 생성해야 합니다.




== 단계

. Provision Workload * 페이지에서 생성할 워크로드 이름을 추가한 다음 워크로드를 생성할 사용 가능 목록에서 클러스터를 선택합니다.
. 선택한 클러스터에 따라 * storage vm * 필드가 해당 클러스터에 사용할 수 있는 스토리지 가상 머신을 필터링합니다. 목록에서 필요한 스토리지 VM을 선택합니다.
+
스토리지 VM에서 지원되는 SMB, NFS, iSCSI 및 FCP 서비스에 따라 호스트 정보 섹션에서 NAS 및 SAN 옵션이 활성화됩니다.

. 스토리지 및 최적화 * 섹션에서 스토리지 용량 및 성능 서비스 레벨을 할당하고 워크로드에 대한 스토리지 효율성 정책을 선택적으로 할당합니다.
+
성능 서비스 수준 사양은 워크로드에 적용되며, 스토리지 효율성 정책 사양은 워크로드 생성 시 볼륨 및 LUN에 적절하게 할당됩니다.

. 작업 부하에 할당한 성능 서비스 수준을 적용하려면 * 성능 제한 적용 * 확인란을 선택합니다. 워크로드에 성능 서비스 수준을 할당하면 워크로드가 생성되는 총계를 통해 해당 성능 서비스 수준에서 정의된 성능 및 용량 목표를 지원할 수 있습니다. 예를 들어, 워크로드에 ""최고 성능""이 할당되면 워크로드를 프로비저닝할 총 용량에는 SSD 스토리지와 같은 "최고 성능" 성능 서비스 수준의 성능 및 용량 목표를 지원할 수 있는 기능이 있어야 합니다.
+
[NOTE]
====
이 확인란을 선택하지 않으면 성능 서비스 수준이 워크로드에 적용되지 않고 대시보드의 워크로드 상태가 미할당 상태로 표시됩니다.

====
. SMB 및/또는 NFS 파일 공유를 생성하는 경우 * nas * 버튼을 선택하십시오. 이 버튼은 스토리지 VM에 필요한 서비스가 활성화되어 있는 경우에만 선택할 수 있습니다.
+
[NOTE]
====
SVM이 SMB 및 NFS 서비스에 대해 활성화된 경우 * Share by NFS * 및 * Share by SMB * 버튼을 선택하고 NFS 및 SMB 프로토콜을 모두 지원하는 파일 공유를 생성할 수 있습니다. SMB 또는 CIFS 공유를 생성하려면 해당 버튼만 선택합니다.

====
+
.. NFS 파일 공유의 경우 파일 공유 볼륨을 액세스할 호스트 또는 네트워크의 IP 주소를 지정합니다. 여러 호스트에 대해 쉼표로 구분된 값을 입력할 수 있습니다.
+
호스트 IP 주소를 추가할 때, SVM과 호스트 세부 정보를 일치시키기 위해 내부 검사가 실행되고 해당 호스트에 대한 엑스포트 정책이 생성되거나 기존 정책이 있는 경우 재사용됩니다. 동일한 호스트에 대해 여러 개의 NFS 공유가 생성된 경우 동일한 호스트에 대해 사용 가능한 내보내기 정책이 모든 파일 공유에 다시 사용됩니다. API를 사용하여 NFS 공유를 프로비저닝할 때 개별 정책의 규칙을 지정하거나 특정 정책 키를 제공하여 정책을 재사용하는 기능을 사용할 수 있습니다.

.. SMB 공유의 경우 SMB 공유에 액세스할 수 있는 사용자 또는 사용자 그룹을 지정하고 필요한 권한을 할당합니다. 각 사용자 그룹에 대해 파일 공유를 생성하는 동안 새 ACL(액세스 제어 목록)이 생성됩니다.


. LUN을 생성하려면 * SAN * 버튼을 선택합니다. 이 버튼은 선택한 스토리지 VM에 필요한 서비스가 활성화되어 있는 경우에만 선택할 수 있습니다.
+
.. 호스트 OS를 선택합니다.
.. LUN에 대한 호스트 매핑을 지정합니다. 기존 이니시에이터 그룹(igroup)을 지정하거나 새 igroup을 LUN에 정의 및 매핑하여 LUN에 액세스할 수 있는 이니시에이터를 제어할 수 있습니다.
+

NOTE: LUN을 프로비저닝하는 동안 새로운 igroup을 생성하는 경우 LUN 생성에 사용하기 위해 다음 검색 주기(최대 15분)까지 기다려야 합니다. 따라서 사용 가능한 igroup 목록에서 기존 igroup을 사용하는 것이 좋습니다.

+
새 igroup을 생성하려면 * Create a new initiator group * 버튼을 선택하고 필요한 정보를 입력하여 igroup을 생성합니다.



. 저장 * 을 클릭합니다.


스토리지 워크로드 목록에 워크로드가 추가됩니다.
