---
permalink: online-help/task-exporting-storage-data-as-reports.html 
sidebar: sidebar 
keywords:  
summary: '데이터를 쉼표로 구분된 값 \(.csv\) 파일 또는 \(.pdf\) 문서로 내보내고 내보낸 데이터를 사용하여 보고서를 작성할 수 있습니다. 예를 들어 해결되지 않은 10개의 중요 이벤트가 있는 경우 이벤트 관리 인벤토리 페이지에서 데이터를 내보내서 보고서를 만든 다음 적절한 조치를 취할 수 있습니다.' 
---
= 보고를 위해 CSV 및 PDF 파일로 데이터 내보내기
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
데이터를 쉼표로 구분된 값으로 내보낼 수 있습니다 (`.csv`) 파일 또는 (`.pdf`) 문서를 작성하고 내보낸 데이터를 사용하여 보고서를 작성합니다. 예를 들어 해결되지 않은 10개의 중요 이벤트가 있는 경우 이벤트 관리 인벤토리 페이지에서 데이터를 내보내서 보고서를 만든 다음 적절한 조치를 취할 수 있습니다.



== 이 작업에 대해

데이터를 로 내보낼 수 있습니다 `.csv` 파일 또는 `.pdf` 스토리지, 네트워크 및 서비스 품질 재고 페이지에서 문서를 작성하고 내보낸 데이터를 사용하여 보고서를 작성합니다.



== 단계

. 다음 작업 중 하나를 수행합니다.
+
[cols="1a,1a"]
|===
| 내보내려는 경우... | 수행할 작업... 


 a| 
이벤트 세부 정보
 a| 
왼쪽 탐색 메뉴에서 * 이벤트 관리 * 를 클릭합니다.



 a| 
스토리지 객체 인벤토리 세부 정보입니다
 a| 
왼쪽 탐색 메뉴에서 * 스토리지 * 또는 * 네트워크 * 를 클릭한 다음 스토리지 객체를 선택합니다. 그런 다음 * 상태 *, * 용량 *, * 성능 * 또는 * 관계 * 보기 중 하나를 선택합니다.



 a| 
스토리지 용량 및 보호 기록 세부 정보
 a| 
스토리지 * > * 애그리게이트 * 또는 * 스토리지 * > * 볼륨 * 을 클릭한 다음 단일 애그리게이트 또는 볼륨을 선택합니다.



 a| 
스토리지 객체 10가지 성능 세부 정보
 a| 
스토리지 * > * 클러스터 * > * 성능/모든 클러스터 * 를 클릭한 다음 클러스터를 선택하고 * 우수 성과 * 탭을 선택합니다. 그런 다음 스토리지 오브젝트 및 성능 카운터를 선택합니다.



 a| 
QoS 정책 그룹 세부 정보
 a| 
왼쪽 탐색 메뉴에서 * 스토리지 * > * QoS 정책 그룹 * 을 클릭합니다.

|===
. 내보내기 * 버튼을 클릭합니다.
. CSV 파일 * 또는 * PDF 문서 * 를 클릭하여 내보내기 요청을 확인합니다.
+
Top Performers 탭에서 보고 있는 단일 클러스터의 통계 보고서 또는 데이터 센터의 모든 클러스터에 대한 통계 보고서를 다운로드할 수 있습니다.

+
파일이 다운로드됩니다.

. 를 엽니다 `.csv` 파일 또는 `.pdf` 해당 응용 프로그램에 문서화.

