---
permalink: online-help/task-viewing-and-adding-vcenter-servers.html 
sidebar: sidebar 
keywords: vCenter server 
summary: '가상 머신(VM\)의 성능을 보고 문제를 해결하려면 관련 vCenter를 Active IQ Unified Manager 인스턴스에 추가해야 합니다.' 
---
= vCenter 서버 보기 및 추가
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VM(가상 머신)의 성능을 보고 문제를 해결하려면 관련 vCenter를 Active IQ Unified Manager 인스턴스에 추가해야 합니다.



== 시작하기 전에

vCenter를 추가하거나 보기 전에 다음을 확인하십시오.

* vCenter 이름을 알고 있습니다.
* 성공적인 검색을 위해 vCenter에 연결할 수 있습니다.
* vCenter를 추가하는 동안 IP 주소를 알고 있고 자격 증명이 있습니다. 자격 증명은 vCenter 관리자 또는 vCenter에 대한 읽기 전용 액세스 권한이 있는 루트 사용자여야 합니다.
* 추가하려는 vCenter는 vSphere 6.5 이상을 실행합니다.
* vCenter Server의 데이터 수집 설정은 5분 간격으로 레벨 3으로 설정됩니다
* 지연 시간 값을 성공적으로 계산할 수 있도록 vCenter의 지연 시간 값은 마이크로초 단위가 아니라 밀리초 단위로 구성됩니다.
* vCenter의 시간은 vCenter의 표준 시간대에 속합니다.




== 이 작업에 대해

추가 및 검색된 모든 vCenter에 대해 Unified Manager는 vCenter 및 ESXi 서버 세부 정보, ONTAP 매핑, 데이터 저장소 세부 정보, 호스팅된 VM 수 등의 구성 데이터를 수집합니다. 또한 구성 요소의 성능 메트릭을 수집합니다.



== 단계

. VMware * > * vCenter * 로 이동하여 목록에서 vCenter를 사용할 수 있는지 확인합니다.
+
[NOTE]
====
vCenter를 사용할 수 없는 경우 vCenter를 추가해야 합니다.

====
+
.. 추가 * 를 클릭합니다.
.. vCenter에 올바른 IP 주소를 추가하고 디바이스에 연결할 수 있는지 확인합니다.
.. vCenter에 대한 읽기 전용 액세스 권한이 있는 관리자 또는 루트 사용자의 사용자 이름 및 암호를 추가합니다.
.. 기본값 외의 다른 포트를 사용하는 경우 사용자 지정 포트 번호를 추가합니다 `443`.
.. 저장 * 을 클릭합니다. 검색이 완료되면 서버 인증서가 표시되어 수락됩니다.
+
인증서를 수락하면 vCenter가 사용 가능한 vCenter 목록에 추가됩니다. 장치를 추가해도 연결된 VM의 데이터 수집은 되지 않으며 예약된 간격으로 수집이 수행됩니다.



. vCenter가 * vCenters * 페이지에서 사용 가능한 경우 해당 상태를 확인합니다. 상태 * 필드 위로 마우스를 가져가면 vCenter가 예상대로 작동하는지 또는 경고 또는 오류가 있는지 여부가 표시됩니다.
+
[NOTE]
====
vCenter를 추가하면 다음 상태를 볼 수 있습니다. 그러나 vCenter를 정확하게 반영하려면 해당 VM의 성능 및 지연 시간 데이터가 1시간 정도 걸릴 수 있습니다.

====
+
** 녹색: 정상 - vCenter가 검색되었으며 성능 메트릭이 성공적으로 수집되었음을 나타냅니다
** 노란색: 경고(예: vCenter Server의 통계 수준이 각 객체에 대한 통계를 얻기 위해 3 이상으로 설정되지 않은 경우)
** 주황색: 오류(예외, 구성 데이터 수집 실패 또는 vCenter에 연결할 수 없음 등의 내부 오류를 나타냄). 열 표시 아이콘(* 표시/숨기기*)을 클릭하여 vCenter 상태에 대한 상태 메시지를 보고 문제를 해결할 수 있습니다.


. vCenter에 연결할 수 없거나 자격 증명이 변경된 경우 vCenter 세부 정보를 편집합니다. vCenter를 선택한 다음 * Edit * 를 클릭합니다.
. VMware vCenter Server * 편집 페이지에서 필요한 내용을 변경합니다.
. 저장 * 을 클릭합니다.
+
검색이 완료되면 vCenter의 상태가 변경됩니다.


