---
settings:
  name: Active IQ Unified Manager 9.7
  internal:
    pdf_enabled: true
    lipi_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  versions:
  - name: Unified Manager를 참조하십시오
    url: "/active-iq-unified-manager-97"
    version-number: '9.7'
  - name: Unified Manager를 참조하십시오
    url: "/active-iq-unified-manager-99"
    version-number: '9.9'
  - name: Unified Manager를 참조하십시오
    url: "/active-iq-unified-manager-98"
    version-number: '9.8'
  - name: Unified Manager를 참조하십시오
    url: "/oncommand-unified-manager-95"
    version-number: '9.5'
  langs: ko-kr,us-en,ja-jp,zh-cn,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: Active IQ Unified Manager 9.7 문서
    url: "/index.html"
  - title: 릴리스 정보
    url: "/release-notes.html"
  - title: 시작하십시오
    entries:
    - title: VMware vSphere를 위한 빠른 시작 설치
      url: "/install-vapp/qsg-vapp.html"
    - title: Linux용 빠른 시작 설치
      url: "/install-linux/qsg-linux.html"
    - title: Windows용 빠른 시작 설치
      url: "/install-windows/qsg-windows.html"
  - section: install-vapp
  - section: install-linux
  - section: install-windows
  - section: config
  - section: online-help
  - section: performance-checker
  - section: health-checker
  - section: data-protection
  - section: reporting
  - section: api-automation
  - title: 법적 고지
    url: "/reference-legal-notices.html"
homepage:
  tiles:
  - title: 시작하십시오
    links:
    - title: 릴리스 정보
      url: "/release-notes.html"
    - title: VMware vSphere를 위한 빠른 시작 설치
      url: "/install-vapp/qsg-vapp.html"
    - title: Linux용 빠른 시작 설치
      url: "/install-linux/qsg-linux.html"
    - title: Windows용 빠른 시작 설치
      url: "/install-windows/qsg-windows.html"
  - title: Configure Unified Manager를 설치합니다
    links:
    - title: VMware vSphere 시스템에 업그레이드를 설치합니다
      url: "/install-vapp/concept-requirements-for-installing-unified-manager.html"
    - title: Linux 시스템에 업그레이드를 설치합니다
      url: install-linux/concept-requirements-for-installing-unified-manager.html
    - title: Windows 시스템에 업그레이드를 설치합니다
      url: "/install-windows/concept-requirements-for-installing-unified-manager.html"
    - title: Unified Manager를 구성합니다
      url: "/config/concept-configuring-unified-manager.html"
  - title: 성능 모니터링
    links:
    - title: 성능 임계값
      url: "/performance-checker/concept-managing-performance-thresholds.html"
    - title: 클러스터 성능
      url: performance-checker/concept-monitoring-cluster-performance-from-the-dashboard.html
    - title: QoS 정책 그룹
      url: "/performance-checker/concept-managing-performance-using-qos-policy-group-information.html"
    - title: 워크로드 분석기입니다
      url: "/performance-checker/concept-troubleshooting-workloads-using-the-workload-analyzer.html"
    - title: 워크로드 성능
      url: "/performance-checker/concept-collecting-data-and-monitoring-workload-performance.html"
    - title: 성능 관리
      url: performance-checker/concept-managing-performance-using-perf-capacity-and-available-iops-information.html
  - title: 스토리지 및 오브젝트 상태 모니터링
    links:
    - title: 클러스터 및 클러스터 오브젝트 상태
      url: online-help/concept-managing-and-monitoring-clusters-and-cluster-object-health.html
    - title: 상태 임계값입니다
      url: "/health-checker/concept-managing-health-thresholds.html"
    - title: AutoSupport 메시지 및 지원 번들을 보냅니다
      url: health-checker/task-send-a-support-bundle-to-technical-support.html
  - title: 데이터 보호 모니터링
    links:
    - title: 보호 관계를 설정합니다
      url: "/data-protection/task-setting-up-protection-relationships-in-unified-manager.html"
    - title: 장애 조치 및 장애 복구를 수행합니다
      url: data-protection/task-performing-a-protection-relationship-failover-and-failback.html
    - title: 보호 관계를 관리합니다
      url: data-protection/concept-managing-and-monitoring-protection-relationships.html
    - title: 보고서를 생성합니다
      url: "/reporting/concept-unified-manager-reporting.html"
  - title: REST API 사용
    links:
    - title: 시작하십시오
      url: "/api-automation/concept-api-url-and-categories.html"
    - title: 스토리지 오브젝트 관리
      url: "/api-automation/concept-data-center-apis.html"
    - title: ONTAP API 액세스
      url: "/api-automation/concept-gateway-apis.html"
    - title: 공통 워크플로우
      url: "/api-automation/concept-workflow-intro.html"
    - title: 스토리지 프로비저닝
      url: api-automation/concept-provisioning-workflow.html
  - title: 더 많은 리소스
    links:
    - title: Unified Manager 비디오
      url: https://www.youtube.com/playlist?list=PLdXI3bZJEw7mp3jFSg0IJgo3oeDQRY-Gl
    - title: Unified Manager 블로그
      url: https://www.netapp.com/blog/#q=active%20iq%20unified%20manager&t=Blogs&sort=%40publish_date_mktg%20descending&layout=card&f:@facet_language_mktg=[English]
    - title: 최신 버전의 Active IQ Unified Manager 설명서
      url: https://docs.netapp.com/us-en/active-iq-unified-manager/index.html
