---
permalink: api-automation/concept-managing-fileshares-api.html 
sidebar: sidebar 
keywords:  
summary: 여기에 나열된 API를 사용하여 CIFS 공유 및 NFS 파일 공유를 확인, 추가 및 삭제할 수 있습니다. 또한 이러한 API를 사용하여 파일 공유에 대한 성능 서비스 수준 및 스토리지 효율성 정책을 할당 및 수정할 수 있습니다. 
---
= 파일 공유 관리
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
여기에 나열된 API를 사용하여 CIFS 공유 및 NFS 파일 공유를 확인, 추가 및 삭제할 수 있습니다. 또한 이러한 API를 사용하여 파일 공유에 대한 성능 서비스 수준 및 스토리지 효율성 정책을 할당 및 수정할 수 있습니다.

스토리지를 할당하기 전에 가상 머신이 생성되고 지원되는 프로토콜을 사용하여 프로비저닝되어야 합니다. 마찬가지로 파일 공유에 스토리지 효율성 정책을 할당하려면 스토리지 효율성 정책을 생성한 후 파일 공유를 생성해야 합니다.



== 파일 공유를 봅니다

다음 방법을 사용하여 Unified Manager 환경에서 사용 가능한 모든 스토리지 워크로드를 볼 수 있습니다. ONTAP 클러스터를 Active IQ Unified Manager의 데이터 소스로 추가하면 해당 클러스터의 스토리지 워크로드가 Unified Manager 인스턴스에 자동으로 추가됩니다. 이 API는 모든 파일 공유를 자동으로 검색하고 Unified Manager 인스턴스에 수동으로 추가합니다. 이 API를 파일 공유 키로 실행하여 특정 파일 공유의 세부 정보를 볼 수 있습니다.

[cols="1a,1a,1a"]
|===
| 범주 | HTTP 동사 | 경로 


 a| 
제공합니다
 a| 
가져오기
 a| 
`/storage-provider/file-shares`

`+/storage-provider/file-shares/{key}+`

|===


== 파일 공유를 추가합니다

다음 방법을 사용하여 SVM에 CIFS 및 NFS 파일 공유를 추가할 수 있습니다. 만들려는 파일 공유의 세부 정보를 입력 매개 변수로 입력해야 합니다. 이 API를 사용하여 FlexGroups를 생성할 수 없습니다.

[cols="1a,1a,1a"]
|===
| 범주 | HTTP 동사 | 경로 


 a| 
제공합니다
 a| 
게시
 a| 
`/storage-provider/file-shares`

|===
[NOTE]
====
ACL(액세스 제어 목록) 매개 변수 또는 엑스포트 정책 매개 변수의 제공 여부에 따라 CIFS 공유 또는 NFS 파일 공유가 생성됩니다. ACL 매개 변수의 값을 제공하지 않으면 CIFS 공유가 생성되지 않고 기본적으로 NFS 공유가 생성되므로 모든 에 액세스할 수 있습니다.

====


== 파일 공유를 삭제합니다

다음 방법을 사용하여 특정 파일 공유를 삭제할 수 있습니다. 특정 파일 공유를 삭제하려면 파일 공유 키를 입력 매개 변수로 입력해야 합니다.

[cols="1a,1a,1a"]
|===
| 범주 | HTTP 동사 | 경로 


 a| 
제공합니다
 a| 
삭제
 a| 
`+/storage-provider/file-shares/{key}+`

|===


== 파일 공유를 수정합니다

다음 메서드를 사용하여 파일 공유를 수정하고 해당 속성을 업데이트할 수 있습니다.

특정 파일 공유를 수정하려면 파일 공유 키를 제공해야 합니다. 또한 업데이트할 속성과 해당 값을 입력해야 합니다.

[NOTE]
====
이 API를 한 번 호출할 때 하나의 속성만 업데이트할 수 있습니다. 여러 업데이트를 하려면 이 API를 여러 번 실행해야 합니다.

====
[cols="1a,1a,1a"]
|===
| 범주 | HTTP 동사 | 경로 


 a| 
제공합니다
 a| 
패치
 a| 
`+/storage-provider/file-shares/{key}+`

|===