---
permalink: install-windows/task-changing-the-jboss-password-on-windows.html 
sidebar: sidebar 
keywords:  
summary: 새로운 맞춤형 JBoss 암호를 생성하여 설치 중에 설정된 기본 암호를 덮어쓸 수 있습니다. 이 작업은 선택 사항이지만 일부 사이트에서는 Unified Manager 설치 기본 설정을 재정의하기 위해 이 보안 기능이 필요할 수 있습니다. 이 작업은 JBoss가 MySQL에 액세스하는 데 사용하는 암호도 변경합니다. 
---
= JBoss 암호 변경
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
새로운 맞춤형 JBoss 암호를 생성하여 설치 중에 설정된 기본 암호를 덮어쓸 수 있습니다. 이 작업은 선택 사항이지만 일부 사이트에서는 Unified Manager 설치 기본 설정을 재정의하기 위해 이 보안 기능이 필요할 수 있습니다. 이 작업은 JBoss가 MySQL에 액세스하는 데 사용하는 암호도 변경합니다.



== 시작하기 전에

* Unified Manager가 설치된 시스템에 대한 Windows 관리자 권한이 있어야 합니다.
* MySQL root 사용자의 암호가 있어야 합니다.
* NetApp에서 제공하는 에 액세스할 수 있어야 합니다 `password.bat` 디렉토리에 있는 스크립트입니다 `\Program Files\NetApp\essentials\bin`.




== 단계

. Unified Manager 호스트 시스템에서 admin 사용자로 로그인합니다.
. Windows 서비스 콘솔을 사용하여 다음 Unified Manager 서비스를 중지합니다.
+
** NetApp Active IQ 구입 서비스(Ocie-au)
** NetApp Active IQ 관리 서버 서비스(Oncommanddsvc)


. 를 시작합니다 `password.bat` 암호 변경 프로세스를 시작하는 스크립트: `C:\Program Files\NetApp\essentials\bin> password.bat resetJBossPassword`
. 메시지가 표시되면 MySQL root 사용자 암호를 입력합니다.
. 메시지가 표시되면 현재 JBoss 사용자 암호를 입력합니다.
+
기본 암호는 입니다 `D11h1aMu@79%`.

. 메시지가 표시되면 새 JBoss 사용자 암호를 입력한 다음 확인을 위해 다시 입력합니다.
+
변경 사항이 있을 때 확인 메시지가 나타나고 새 JBoss 사용자 암호를 묻는 메시지가 마지막으로 표시됩니다.

. 새 JBoss 사용자 암호를 한 번 더 입력합니다.
. 스크립트가 완료되면 Windows 서비스 콘솔을 사용하여 Unified Manager 서비스를 시작합니다.
+
** NetApp Active IQ 관리 서버 서비스(Oncommanddsvc)
** NetApp Active IQ 구입 서비스(Ocie-au)


. 모든 서비스가 시작되면 Unified Manager UI에 로그인할 수 있습니다.

