---
permalink: install-windows/task-upgrading-mysql-on-windows-ocum.html 
sidebar: sidebar 
keywords: Active IQ Unified Manager 
summary: Unified Manager가 설치된 Windows 서버에서 MySQL을 상위 버전으로 업그레이드하여 보안 취약점에 대한 수정 사항을 확인할 수 있습니다. 사소한 업그레이드의 경우 MySQL의 기본 버전은 8.0.17 이상이어야 합니다. 시스템에 설치된 MySQL 버전이 8.0.17 이전인 경우 Unified Manager 9.7 업그레이드 프로세스에서 MySQL을 8.0.17로 자동 업그레이드합니다. MySQL의 독립 실행형 업그레이드를 이전 버전에서 8.0.17로 실행해서는 안 됩니다. 
---
= MySQL 업그레이드
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager가 설치된 Windows 서버에서 MySQL을 상위 버전으로 업그레이드하여 보안 취약점에 대한 수정 사항을 확인할 수 있습니다. 사소한 업그레이드의 경우 MySQL의 기본 버전은 8.0.17 이상이어야 합니다. 시스템에 설치된 MySQL 버전이 8.0.17 이전인 경우 Unified Manager 9.7 업그레이드 프로세스에서 MySQL을 8.0.17로 자동 업그레이드합니다. MySQL의 독립 실행형 업그레이드를 이전 버전에서 8.0.17로 실행해서는 안 됩니다.



== 시작하기 전에

[NOTE]
====
시스템에 설치된 MySQL 버전이 5.7인 경우 MySQL을 버전 8.0.17로 직접 업그레이드하지 마십시오. 애플리케이션 데이터가 손실됩니다.

====
* Unified Manager가 설치된 시스템에 대한 Windows 관리자 권한이 있어야 합니다.
* MySQL root 사용자의 암호가 있어야 합니다.




== 단계

. Unified Manager 호스트 시스템에서 admin 사용자로 로그인합니다.
. 대상 시스템에 적절한 버전의 MySQL을 다운로드합니다.
. Windows 서비스 콘솔을 사용하여 다음 Unified Manager 서비스를 중지합니다.
+
** NetApp Active IQ 구입 서비스(Ocie-au)
** NetApp Active IQ 관리 서버 서비스(Oncommanddsvc)
** MYSQL8


. 를 클릭합니다 `.msi` 패키지를 사용하여 MySQL 업그레이드를 호출하고 화면의 지침에 따라 업그레이드를 완료합니다.
. Windows 서비스 콘솔을 사용하여 Unified Manager 서비스를 시작합니다.
+
** MYSQL8
** NetApp Active IQ 관리 서버 서비스(Oncommanddsvc)
** NetApp Active IQ 구입 서비스(Ocie-au)



